name: tests

on:
  push:
  pull_request:
  workflow_dispatch:
    swow_ref:
      description: 'Using Swow git ref'
      required: false
      default: 'develop'
  schedule:
    - cron: '0 3 * * *'

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, 'macos-latest']
        php-version: ['8.0', '8.1']
      max-parallel: 4
    steps:
      - name: Checkout Self
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: redis, pdo, pdo_mysql, bcmath, curl, openssl
          tools: phpize
          coverage: none
      - name: Checkout Swow
        uses: actions/checkout@v2
        with:
          repository: swow/swow
          ref: ${{ (github.event.inputs && github.event.inputs.swow_ref) || 'develop' }}
          path: swow
      - name: Build Swow
        run: |
          if [ ${{ runner.os }} = 'Linux' ]
          then
            printf "::group::\033[1mInstall dependencies\033[0m\n"
            sudo apt-get update
            sudo apt-get install -yqq libcurl4-openssl-dev
          fi
          cd swow/ext
          printf "::group::\033[1mRun phpize\033[0m\n"
          phpize
          printf "::group::\033[1mStart configure\033[0m\n"
          ./configure \
            --enable-swow-debug \
            --enable-swow-ssl=${{ runner.os == 'Linux' && 'yes' || '/usr/local/opt/openssl' }} \
            --enable-swow-curl=${{ runner.os == 'Linux' && 'yes' || '/usr/local/opt/curl' }}
          printf "::group::\033[1mStart build Swow\033[0m\n"
          make -j "$(${{ runner.os == 'Linux' && 'nproc' || 'sysctl -n hw.logicalcpu' }})"
          printf "::group::\033[1mInstall Swow\033[0m\n"
          ${{ runner.os == 'Linux' && 'sudo' || ''}} make install-modules
          printf "::group::\033[1mEnable Swow\033[0m\n"
          inipath=`php --ini | sed -n 's/^Scan for additional .ini files in: //p'`
          sudo sh -c "echo extension=swow > ${inipath}/swow.ini"
          php --ri swow
      - name: Setup Packages
        run: composer update -o
      - name: Run Analyse
        run: |
          composer analyse src
      # - name: Run Test Cases
      #   run: |
      #     composer test