name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

env:
  PHP_CS_FIXER_IGNORE_ENV: 1
  SKIP_SWOW_REQUIRED_EXTENSION_CHECK: 1
  SWOW_ALIAS_VERSION: 1.2.0

jobs:
  ci:
    name: Test for PHP ${{ matrix.php }} - Swow ${{ matrix.swow }} - Workerman ${{ matrix.workerman }} on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        php: ['8.0', '8.1', '8.2']
        swow: ['1.2.*']
        workerman: ['4.0', '5.0']
        exclude:
          - php: 8.0
            workerman: 5.0
      max-parallel: 16
    steps:
      - name: Checkout Self
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath, curl, openssl
          tools: phpize
          coverage: none
      - name: Setup Packages
        run: |
          composer update -o
          composer require workerman/workerman:^${{ matrix.workerman }}
      - name: Setup Swow
        run: |
          composer require swow/swow:${{ matrix.swow }}
        if: matrix.swow != 'develop'
      - name: Setup Swow (develop)
        run: |
          composer require swow/swow:"dev-develop as ${{env.SWOW_ALIAS_VERSION}}"
          sudo ./vendor/bin/swow-builder --install
        if: matrix.swow == 'develop'
      - name: Build Swow
        run: |
          sudo ./vendor/bin/swow-builder --install
          inipath=`php --ini | sed -n 's/^Scan for additional .ini files in: //p'`
          sudo sh -c "echo extension=swow > ${inipath}/swow.ini"
          php --ri swow
      - name: Run Cs Fixer
        run: php vendor/bin/php-cs-fixer fix src --dry-run
      - name: Run Analyse
        run: |
          composer analyse src
      # - name: Run Test Cases
      #   run: |
      #     composer test