name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  ci:
    name: Test for PHP ${{ matrix.php }} with Swow ${{ matrix.swow }} on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        php: ['8.0', '8.1', '8.2']
        swow: ['1.1.0', '1.0.0', 'develop']
      max-parallel: 16
    steps:
      - name: Checkout Self
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath, curl, openssl
          tools: phpize
          coverage: none
      - name: Setup Packages
        run: |
          composer update -o
      - name: Build Swow
        run: |
          composer remove swow/swow
          if [ "${{ matrix.swow }}" = "develop" ]; then
            composer require swow/swow:dev-${{ matrix.swow }}
          else
            composer require swow/swow:~${{ matrix.swow }}
          fi
          sudo ./vendor/bin/swow-builder --install
          inipath=`php --ini | sed -n 's/^Scan for additional .ini files in: //p'`
          sudo sh -c "echo extension=swow > ${inipath}/swow.ini"
          php --ri swow
      - name: Run Cs Fixer
        run: |
          if [ "${{ matrix.php }}" = "8.2" ]; then
            PHP_CS_FIXER_IGNORE_ENV=true php vendor/bin/php-cs-fixer fix src --dry-run
          else
            php vendor/bin/php-cs-fixer fix src --dry-run
          fi
      - name: Run Analyse
        run: |
          composer analyse src
      # - name: Run Test Cases
      #   run: |
      #     composer test